version: '3.9'

services:
  react-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: python:3.10
    working_dir: /usr/src/app/api
    volumes:
      - ./src/api:/usr/src/app/api
    command: python FlaskApp.py
    ports:
      - "5000:5000"
